### ISSUE TITLE
Differenciate new accounts 

### ISSUE THREAD

**Issue by KanchiMoe** [CrustyJew/DirtBag#4]
In reports, when it says "New Reddit Acct", can it say if the account is below our limits (and missed by AutoMod) or above but still quite new.

For example (current):

> CodeWord_Dirtbag: ...., New Reddit Acct, Monetized by ...

New:

> CodeWord_Dirtbag: ...., New Reddit Acct (below limits), Monetized by ...

To show it's below the limits set in AutoModerator.

> CodeWord_Dirtbag: ...., New Reddit Acct, Monetized by ...

If it's above the limits in AutoMod, but still under a month old or something.

**Comment by CrustyJew** [comment]
Probably won't do this as if it's below automod, it's going to be removed before dirtbag gets to it anyway
